### ISSUE TITLE
Webpack UglifyJs Error

### ISSUE THREAD

**Issue by yezongyang** [mjbp/storm-sticky#1]
Unexpected token punc «(», expected punc «:» [js/16.43fbd6b8.chunk.js:1605,6]

<img width="432" alt="0b374f3e-16a7-48e5-b154-832f77a63eae" src="https://cloud.githubusercontent.com/assets/8924156/24836075/1061517e-1d45-11e7-8c95-de43a35027f3.png">

**Comment by mjbp** [comment]
Almost a year late, but webpack uglifyjs doesn't like ES6, see https://github.com/webpack/webpack/issues/5858#issuecomment-338144186
